### ISSUE TITLE
Way to display nothing?

### ISSUE THREAD

**Issue by hw2007** [ThePcCreator/Arduino-4-Digit-7-Segment-Display-Library#1]
Is there a way to just display nothing on the screen for a certain amount of loops?

Currently I can do something like this:

writeNum(1234, 1000);
delay(500);

and it is blank for around the same time as it displays the number, but it's not exact. I'd like to be able to do something like this instead:

writeNum(1234, 1000);
clearDisplay(1000);

**Comment by ThePcCreator** [comment]
Hello, thanks for reaching out to me. I am looking further into this. Also, just by curiosity, how did you find my library?

**Comment by hw2007** [comment]
> Hello, thanks for reaching out to me. I am looking further into this. Also, just by curiosity, how did you find my library?

I was looking for info on how to control these seven segment displays, and ran into a post (i think it was on stackoverflow) where you commented saying you had made a library to control them, and linked to it.

**Comment by ThePcCreator** [comment]
Hello, sorry for the long wait. In the attached file, there is a function called `clearDisplay` with how many loops as the argument. The loops are the same length as the loops of `writeNum`. Also, in the new code, if you write a four digit number or a one digit number, the the loops will be the same length. Thank you again for your patience! 
--- ThePcCreator
[Display_Controller_New.zip](https://github.com/ThePcCreator/Arduino-4-Digit-7-Segment-Display-Library/files/14030879/Display_Controller_New.zip)
